Make shit more understandable

diff --git a/run_test b/run_test
--- a/run_test
+++ b/run_test
@@ -241,56 +241,56 @@ if [ $? -ne 0 ]; then
 	exit 1
 fi
 
-#rm -rf $output_dir
-#mkdir $output_dir
+rm -rf $output_dir
+mkdir $output_dir
 
 any_error=0
 
 # Start by compiling everything that should be compiled
-#echo "Compling code"
-#for file in $(ls $compile_tests $execute_tests $nonexecute_tests); do
-	#compile_ok $file
-	#if [ $? -ne 0 ]; then
-		#any_error=1
-	#fi
-#done
+echo "Compling code"
+for file in $(ls $compile_tests $execute_tests $nonexecute_tests); do
+	compile_ok $file
+	if [ $? -ne 0 ]; then
+		any_error=1
+	fi
+done
 
-#if [ $any_error -ne 0 ]; then
-	#echo "Previous test failed. Not continuing"
-	#exit 1
-#fi
+if [ $any_error -ne 0 ]; then
+	echo "Previous test failed. Not continuing"
+	exit 1
+fi
 
-#echo -e "\n====================================\n"
+echo -e "\n====================================\n"
 
-#echo "Compiling code that should fail"
+echo "Compiling code that should fail"
 
-#for file in $(ls $noncompile_tests); do
-	#compile_fail $file
-	#if [ $? -ne 0 ]; then
-		#any_error=1
-	#fi
-#done
+for file in $(ls $noncompile_tests); do
+	compile_fail $file
+	if [ $? -ne 0 ]; then
+		any_error=1
+	fi
+done
 
-#if [ $any_error -ne 0 ]; then
-	#echo "Previous test failed. Not continuing"
-	#exit 1
-#fi
+if [ $any_error -ne 0 ]; then
+	echo "Previous test failed. Not continuing"
+	exit 1
+fi
 
-#echo -e "\n====================================\n"
+echo -e "\n====================================\n"
 
-#echo "Assembling"
+echo "Assembling"
 
-#for file in $(ls $execute_tests $nonexecute_tests $compile_tests); do
-	#assemble $file
-	#if [ $? -ne 0 ]; then
-		#any_error=1
-	#fi
-#done
+for file in $(ls $execute_tests $nonexecute_tests $compile_tests); do
+	assemble $file
+	if [ $? -ne 0 ]; then
+		any_error=1
+	fi
+done
 
-#if [ $any_error -ne 0 ]; then
-	#echo "Previous test failed. Not continuing"
-	#exit 1
-#fi
+if [ $any_error -ne 0 ]; then
+	echo "Previous test failed. Not continuing"
+	exit 1
+fi
 
 echo "Running execution test"
 for file in $(ls $execute_tests); do
