Fix borken testcases and improve test code

diff --git a/run_test b/run_test
--- a/run_test
+++ b/run_test
@@ -177,10 +177,13 @@ function generate_output_file() {
 	_javac_out=`$javac -d "$_out" $_java_file 2>&1`
 	if [ $? -eq 0 ]; then
 		# Run the created program!
-		java -cp $_out $(find_main_class $_java_file) > "$_file.output" 2>> "$_out/error.log"
+		java -cp $_out $(find_main_class $_java_file) > "$_file.output" 2> "$_out/error.log"
 		if [ $? -eq 0 ]; then 
 			return 0
 		else
+			echo "The executed command was:" >> "$_out/error.log"
+			echo "java -cp $_out $(find_main_class $_java_file)" >> "$_out/error.log" 
+			rm "$_file.output"
 			return 2
 		fi
 	else
@@ -221,7 +224,8 @@ function execute_test() {
 		ex=$?
 		if [ $ex -eq 0 ]; then
 			_program_outfile="$output_dir/$_dirname/program.output"
-			java -cp $_out $(find_main_class $_file) > "$_program_outfile"
+			_program_errfile="$output_dir/$_dirname/program.err"
+			java -cp $_out $(find_main_class $_file) > "$_program_outfile" 2>"$_program_errfile"
 			ex=$?
 			if [ $ex -eq 0 ]; then
 				_diff_file="$output_dir/$_dirname/output.diff"
@@ -239,8 +243,8 @@ function execute_test() {
 				fi
 			else
 				echo -e "$txtred JVM ERROR $txtrst"
-				echo "JVM Output:"
-				echo -e "$_res\n"
+				echo java -cp $_out $(find_main_class $_file) "> \"$_program_outfile\" 2>\"$_program_errfile\""
+				cat "$_program_errfile"
 				return 1
 			fi
 		else
@@ -273,56 +277,56 @@ if [ $? -ne 0 ]; then
 	exit 1
 fi
 
-#rm -rf $output_dir
-#mkdir $output_dir
+rm -rf $output_dir
+mkdir $output_dir
 
-#any_error=0
+any_error=0
 
-## Start by compiling everything that should be compiled
-#echo "Compling code"
-#for file in $(ls $compile_tests $execute_tests $nonexecute_tests); do
-	#compile_ok $file
-	#if [ $? -ne 0 ]; then
-		#any_error=1
-	#fi
-#done
+# Start by compiling everything that should be compiled
+echo "Compling code"
+for file in $(ls $compile_tests $execute_tests $nonexecute_tests); do
+	compile_ok $file
+	if [ $? -ne 0 ]; then
+		any_error=1
+	fi
+done
 
-#if [ $any_error -ne 0 ]; then
-	#echo "Previous test failed. Not continuing"
-	#exit 1
-#fi
+if [ $any_error -ne 0 ]; then
+	echo "Previous test failed. Not continuing"
+	exit 1
+fi
 
-#echo -e "\n====================================\n"
+echo -e "\n====================================\n"
 
-#echo "Compiling code that should fail"
+echo "Compiling code that should fail"
 
-#for file in $(ls $noncompile_tests); do
-	#compile_fail $file
-	#if [ $? -ne 0 ]; then
-		#any_error=1
-	#fi
-#done
+for file in $(ls $noncompile_tests); do
+	compile_fail $file
+	if [ $? -ne 0 ]; then
+		any_error=1
+	fi
+done
 
-#if [ $any_error -ne 0 ]; then
-	#echo "Previous test failed. Not continuing"
-	#exit 1
-#fi
+if [ $any_error -ne 0 ]; then
+	echo "Previous test failed. Not continuing"
+	exit 1
+fi
 
-#echo -e "\n====================================\n"
+echo -e "\n====================================\n"
 
-#echo "Assembling"
+echo "Assembling"
 
-#for file in $(ls $execute_tests $nonexecute_tests $compile_tests); do
-	#assemble $file
-	#if [ $? -ne 0 ]; then
-		#any_error=1
-	#fi
-#done
+for file in $(ls $execute_tests $nonexecute_tests $compile_tests); do
+	assemble $file
+	if [ $? -ne 0 ]; then
+		any_error=1
+	fi
+done
 
-#if [ $any_error -ne 0 ]; then
-	#echo "Previous test failed. Not continuing"
-	#exit 1
-#fi
+if [ $any_error -ne 0 ]; then
+	echo "Previous test failed. Not continuing"
+	exit 1
+fi
 
 echo "Running execution test"
 for file in $(ls $execute_tests); do
